# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: 'Nathan Allaire '
CodeOfConductContact: 'Nathan Allaire '
Indentation: 4
JuliaMinVersion: '1.9'
License: MPL-2.0
LicenseCopyrightHolders: Nathan Allaire
PackageName: IR2Reg
PackageOwner: nathanemac
PackageUUID: d8b20677-8476-5485-a89f-d14abca248d9
_commit: v0.10.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
