name: Docs

on:
    push:
        branches:
            - main
        tags:
            - "*"
    pull_request:
        branches:
            - main

jobs:
    docs:
        name: Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Nécessaire pour Documenter.jl
            - name: Set up Julia
              uses: julia-actions/setup-julia@v2
              with:
                  version: "1.9"
            - name: Install dependencies
              run: |
                  julia --project=docs -e '
                    using Pkg
                    Pkg.develop(PackageSpec(path=pwd()))
                    Pkg.instantiate()'
            - name: Build and deploy documentation
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  julia --project=docs docs/make.jl
